In [66]:
import numpy as np

In [67]:
print(np.sqrt(49))

7.0


In [68]:
my_list=[1,2,3]
#converting the lists into arrays
v = np.array(my_list)
v

array([1, 2, 3])

In [69]:
my_list1=[4,5,6]
my_list

[1, 2, 3]

In [70]:
print(type(my_list1))

<class 'list'>


In [71]:
v

array([1, 2, 3])

In [72]:
print(v)

[1 2 3]


In [73]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
#Multiplication of Matrices
mul = np.matmul(mat,v)
mul

array([14, 32, 50])

In [75]:
div = np.divide(mat,v)

In [76]:
div

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [77]:
print(div)

[[1.  1.  1. ]
 [4.  2.5 2. ]
 [7.  4.  3. ]]


In [78]:
my_list = list(range(1,11))
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [79]:
new_list = my_list.copy()
new_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [80]:
#Slicing 
new_list[:6]

[1, 2, 3, 4, 5, 6]

In [81]:
new_list[2:4]

[3, 4]

In [82]:
new_list[1:8]

[2, 3, 4, 5, 6, 7, 8]

In [83]:
new_list[:8]

[1, 2, 3, 4, 5, 6, 7, 8]

In [84]:
new_list[4:]

[5, 6, 7, 8, 9, 10]

In [85]:
new_list[:-2]

[1, 2, 3, 4, 5, 6, 7, 8]

In [86]:
new_list[9:3:-1]

[10, 9, 8, 7, 6, 5]

In [87]:
new_list[:10:2]

[1, 3, 5, 7, 9]

In [88]:
new_list[1:10:2]

[2, 4, 6, 8, 10]

In [89]:
v1 = np.array(['blue', 'red', 'orange', 'purple', 'purple', 'orange', 'red', 6])
print(v1)

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'red' '6']


In [90]:
print(np.unique(v1))

['6' 'blue' 'orange' 'purple' 'red']


In [91]:
#Syntax
mat1= np.ones((3,5))
print(mat1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [92]:
mat2 = np.zeros([5,3])
print(mat2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 4th Lecture

In [93]:
v = np.array(my_list)
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


In [94]:
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
v = list(range(1,11))
v

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [96]:
#list comprehensions using for loop
new_list = [x for x in range(1,11)]
new_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [97]:
#Printing numbers less than or equal to 5
new_list = [x for x in range(1,11) if x<=5]
new_list

[1, 2, 3, 4, 5]

In [98]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
new_list = [x for x in fruits]
new_list #copy function 

['apple', 'banana', 'cherry', 'kiwi', 'mango']

In [99]:
my_list = fruits.copy()
my_list
del my_list

In [100]:
new_list=[x.upper() for x in fruits ]

In [101]:
new_list

['APPLE', 'BANANA', 'CHERRY', 'KIWI', 'MANGO']

In [102]:
new_list = [x.lower() for x in fruits]

In [103]:
new_list

['apple', 'banana', 'cherry', 'kiwi', 'mango']

In [104]:
new_list = []
#Indentation
for x in fruits:
    if "e" in x:
        new_list.append(x)
new_list

['apple', 'cherry']

# 5th Lecture


In [1]:
import numpy as np

In [2]:
#Converting lists into arrays
my_list = [5,8,1]
v= np.array(my_list)
v

array([5, 8, 1])

In [3]:
print(v)

[5 8 1]


In [6]:
mat=np.array([[1,2,3],[9,11,5],[4,1,7]])
print(mat)

[[ 1  2  3]
 [ 9 11  5]
 [ 4  1  7]]


In [7]:
#To print a transpose of a matrix
mat.T

array([[ 1,  9,  4],
       [ 2, 11,  1],
       [ 3,  5,  7]])

In [9]:
print('The minimum value of matrix is', np.min(mat))#min value
print('The maximum value of matrix is',np.max(mat))#max value
print('The mean value of matrix is',np.mean(mat))#mean
print('The standard deviation of matrix is',np.std(mat))#Standard Deviation

The minimum value of matrix is 1
The maximum value of matrix is 11
The mean value of matrix is 4.777777777777778
The standard deviation of matrix is 3.3591592128513272


In [13]:
v = np.arange(1,16)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
my_list = list(range(1,11))

In [12]:
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
v1 = np.arange(5,27,7)
print(v1)

[ 5 12 19 26]


In [23]:
#Creating a 2x5 matrix
mat1= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(mat1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
#To check the number of rows and columns in a matrix
mat1.shape

(2, 5)

In [26]:
#Reshaping the 2x5 matrix into a 5x2 matrix
mat1_reshape = mat1.reshape(5,2)
print(mat1_reshape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [27]:
mat1_reshape.shape

(5, 2)

In [30]:
#linspace- It spreads out evenly spaced variables
v2= np.linspace(0,5,5)
print(v2)

[0.   1.25 2.5  3.75 5.  ]


In [32]:
#Generating a series of random numbers in a 5x5 matrix using Numpy
random = np.random.randn(5,5)
(random)

array([[-1.19324708,  0.24819151, -0.10599216, -0.6095793 ,  0.70261506],
       [ 0.29808846, -0.19732284, -1.27295541,  0.87409025, -0.18450826],
       [-0.80955348,  0.47125456, -0.01891403,  3.00736712,  0.17039289],
       [-1.15697858,  0.39062861,  0.49436567, -0.50111106,  0.56776245],
       [-0.53671431, -0.60770764,  0.63235961,  0.22027116, -0.94836829]])

In [35]:
random =np.random.randn(10,5)
random

array([[-0.04451788,  1.46099407, -1.36306815,  1.99355467,  1.10468535],
       [-0.60310726,  0.79654001,  0.34062825, -0.27449868, -0.7226277 ],
       [-0.14590282, -0.96883602, -0.00622914,  0.27924758, -2.04195941],
       [ 0.08588011,  0.31428821,  0.1214707 ,  1.01650704,  0.93502855],
       [ 0.28012089, -1.88461234,  0.42841703,  0.35558447, -0.36408991],
       [-1.78921296, -0.21383005, -0.38481737, -0.12935058, -0.62934028],
       [ 0.32824575,  1.5078809 , -1.18386966, -0.96414418,  1.2623092 ],
       [ 1.5261873 , -1.33391236, -0.90823136,  1.16635721, -0.56904068],
       [-1.88158079,  0.54308431, -0.30239744, -2.74536449,  0.78678903],
       [-0.62094301,  0.42912171,  1.33648779,  1.32305118,  2.08281191]])

In [36]:
random =np.random.randn(3,3)
random

array([[-0.74005692,  0.17785141, -0.07981462],
       [ 0.94693371,  0.66672299,  0.15335211],
       [ 0.15056371, -0.54489739, -0.80585955]])

In [46]:
print(random[0:1,2])

[-0.07981462]
